TinyPlants/TinyPlants/Models/ApplicationUser.cs
using System;
using Microsoft.AspNetCore.Identity;

namespace TinyPlants.Models
{
    public class ApplicationUser : IdentityUser
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}

TinyPlants/TinyPlants/Models/ErrorViewModel.cs
using System;

namespace TinyPlants.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TinyPlants/TinyPlants/Models/Interfaces/IInventoryManager.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace TinyPlants.Models.Interfaces
{
    public interface IInventoryManager
    {
        Task<Product> CreateProduct(Product product);
        Task DeleteProduct(int id);
        Task<List<Product>> GetProducts();
        Task<Product> GetProduct(int id);
        Task UpdateProduct(Product product);
    }
}

TinyPlants/TinyPlants/Models/Product.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace TinyPlants.Models
{
    public class Product
    {
        public int ID { get; set; }
        public string Sku { get; set; }
        public string Name { get; set; }
        [Column(TypeName = "money")]
        public decimal Price { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public bool IsFeatured { get; set; }
    }
}

TinyPlants/TinyPlants/Models/Services/InventoryManager.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using TinyPlants.Data;
using TinyPlants.Models.Interfaces;

namespace TinyPlants.Models.Services
{
    public class InventoryManager : IInventoryManager
    {
        private readonly StoreDbContext _context;

        public InventoryManager(StoreDbContext context)
        {
            _context = context;
        }

        public async Task<Product> CreateProduct(Product product)
        {
            _context.Entry(product).State = EntityState.Added;

            await _context.SaveChangesAsync();

            return product;
        }

        public async Task DeleteProduct(int id)
        {
            var product = await GetProduct(id);

            _context.Entry(product).State = EntityState.Deleted;

            await _context.SaveChangesAsync();
        }

        public async Task<Product> GetProduct(int id)
        {
            var product = await _context.Products.FindAsync(id);

            return product;
        }

        public async Task<List<Product>> GetProducts()
        {
            var products = await _context.Products.ToListAsync();

            return products;
        }

        public async Task UpdateProduct(Product product)
        {
            _context.Products.Update(product);

            await _context.SaveChangesAsync();
        }
    }
}

TinyPlants/TinyPlants/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TinyPlants.Models;

namespace TinyPlants.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TinyPlants/TinyPlants/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TinyPlants.Models.Interfaces;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TinyPlants.Controllers
{
    public class InventoryController : Controller
    {
        private readonly IInventoryManager _inventories;

        public InventoryController(IInventoryManager inventories)
        {
            _inventories = inventories;
        }

        // GET: /<controller>/
        public async Task<IActionResult> IndexAsync()
        {
            return View(await _inventories.GetProducts());
        }
    }
}

TinyPlants/TinyPlants/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TinyPlants/TinyPlants/Views/Inventory/Index.cshtml
@model IEnumerable<TinyPlants.Models.Product>
@{
    ViewData["Title"] = "Inventory Management";
    Layout = "_Layout";
}
<div class="container">
    <h1>Inventory</h1>
    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <form asp-controller="Inventory" asp-action="Index" method="get">
        <p>
            Item Name: <input type="text" name="SearchString">
            <input type="submit" value="Filter" />
        </p>
    </form>
    <table class="table">
        <thead class="text-center">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Image)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Sku)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsFeatured)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <img src="@Html.DisplayFor(modelItem => item.Image)" width="100" height="100" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sku)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsFeatured)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ID">Edit</a>
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a>
                        <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

TinyPlants/TinyPlants/Views/Products/Index.cshtml
@{
    ViewData["Title"] = "Products Page";
}

<div class="text-center">
    <h1 class="display-4">Products</h1>
</div>

TinyPlants/TinyPlants/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TinyPlants</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" href="/images/favicon.png">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/images/logo.svg" width="30" height="30" class="d-inline-block align-top" alt="logo image">
                    TINY PLANTS
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            &copy; 2020 - TINY PLANTS
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>